#!/bin/sh
TAUROOT=/home/ra000007/a03106/tau-2.24.1
MACHINE=x86_64
OLDJDK=@OLDJDK@
TAU_LIBDIR=${TAUROOT}/${MACHINE}/lib


if [ $OLDJDK = yes ]
then
  echo "Java 1.4 or better required.  Try compiling TAU with -slog2"
  exit 1
fi


# Set CLASSPATH to various jar's needed by the converter
TAU_CLASSPATH=${TAU_LIBDIR}/TAU_tf.jar:${TAU_LIBDIR}/traceTOslog2.jar:${TAU_LIBDIR}/tau2slog2.jar

MAIN_CLASS=edu/uoregon/tau/Tau2Slog2
MEMORY="-Xmx500m"
if [ -n "${JAVA_MEMORY}" ]; then
    MEMORY="-Xmx${JAVA_MEMORY}m"
fi
if [ -z "${TAU_LIBDIR}" -o "${TAU_LIBDIR}" = "/lib" ]; then
    echo "TAU_LIBDIR is NOT set!"
    exit 1
fi
echo "Use ${MEMORY}MB"
java $MEMORY -Xms32m -cp ${TAU_CLASSPATH} ${MAIN_CLASS} $@

